[project]
name = 'mental-health-companion'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.mood-tracker]
path = 'contracts/mood-tracker.clar'
clarity_version = 3
epoch = '3.2'

[contracts.therapy-bot]
path = 'contracts/therapy-bot.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
